
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHARESPECIAL = 39;
  public static final int FUNCTION = 4;
  public static final int OPSUM = 31;
  public static final int CHAR = 20;
  public static final int DECISION = 47;
  public static final int QUESTIONMARK = 46;
  public static final int OPDECLARACION = 28;
  public static final int DECREMENTADOR = 49;
  public static final int INTEGER = 21;
  public static final int INT = 14;
  public static final int PUNTOCOMA = 38;
  public static final int ASTERISCO = 17;
  public static final int CURLYDER = 45;
  public static final int FOR = 35;
  public static final int OPBOOL = 26;
  public static final int WRITE = 7;
  public static final int IDENTIFICADOR = 50;
  public static final int RECORD = 23;
  public static final int TYPE = 22;
  public static final int BOOL = 16;
  public static final int STRING1 = 24;
  public static final int BEGIN = 2;
  public static final int OPREL = 30;
  public static final int NUM = 51;
  public static final int MAIN = 10;
  public static final int IF = 11;
  public static final int CONSTSTRING = 54;
  public static final int DOT = 36;
  public static final int PARIZQ = 41;
  public static final int EOF = 0;
  public static final int BOOLEAN = 25;
  public static final int RETURN = 9;
  public static final int INCREMENTADOR = 48;
  public static final int EQUAL = 29;
  public static final int BRACKETIZQ = 42;
  public static final int error = 1;
  public static final int PROGRAM = 6;
  public static final int COMA = 37;
  public static final int VOID = 15;
  public static final int NUMREAL = 52;
  public static final int ASIGNACION = 27;
  public static final int ELSE = 12;
  public static final int READ = 8;
  public static final int WHILE = 34;
  public static final int FLOAT = 19;
  public static final int OPCONDICIONALES = 33;
  public static final int THEN = 13;
  public static final int CURLYIZQ = 44;
  public static final int END = 3;
  public static final int CONSTCHAR = 53;
  public static final int PARDER = 40;
  public static final int BRACKETDER = 43;
  public static final int VAR = 18;
  public static final int OPMULT = 32;
  public static final int PROCEDURE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "FUNCTION",
  "PROCEDURE",
  "PROGRAM",
  "WRITE",
  "READ",
  "RETURN",
  "MAIN",
  "IF",
  "ELSE",
  "THEN",
  "INT",
  "VOID",
  "BOOL",
  "ASTERISCO",
  "VAR",
  "FLOAT",
  "CHAR",
  "INTEGER",
  "TYPE",
  "RECORD",
  "STRING1",
  "BOOLEAN",
  "OPBOOL",
  "ASIGNACION",
  "OPDECLARACION",
  "EQUAL",
  "OPREL",
  "OPSUM",
  "OPMULT",
  "OPCONDICIONALES",
  "WHILE",
  "FOR",
  "DOT",
  "COMA",
  "PUNTOCOMA",
  "CHARESPECIAL",
  "PARDER",
  "PARIZQ",
  "BRACKETIZQ",
  "BRACKETDER",
  "CURLYIZQ",
  "CURLYDER",
  "QUESTIONMARK",
  "DECISION",
  "INCREMENTADOR",
  "DECREMENTADOR",
  "IDENTIFICADOR",
  "NUM",
  "NUMREAL",
  "CONSTCHAR",
  "CONSTSTRING"
  };
}

